### ISSUE TITLE
Is there a way to automatically push the newly created tag?

### ISSUE THREAD

**Issue by niaodan2b** [s3xysteak/tauri-version#2]
Currently I have this in my package.json
```
"scripts": {
    "release": "tauri-version patch --no-lock -m \"release v%s\" && git push --tags"
}
```
So I can do `npm run release` every time to make a new release.

But I don't want to push all my local tags when only the newly created one is needed, I could do `git push origin [tagname]` instead but `[tagname]` changes every time. So I'm wondering if there's a way to achieve this?

Or alternatively, is it possible to make the release tag annotated, so that `git push --follow-tags` would work?

Big thanks for this tool

**Comment by s3xysteak** [comment]
Should be fixed in `v0.5.0`. Now we use `git tag --annotate --message="same as commit message" v0.0.1`
